### ISSUE TITLE
2d segmentation 

### ISSUE THREAD

**Issue by mariamhrr** [NifTK/NiftyNet#13]
Hello,  do you have a conf.ini file example for 2d image segmentation ? Can I feed a network with png images and png labels ?

**Comment by wyli** [comment]
Hi @mariamhrr , at the moment we don't have any concrete example of 2d image segmentation and png format is not supported. Contributions are welcomed!

**Comment by imaluengo** [comment]
@mariamhrr @wyli Since the merge of [image-loader](https://github.com/NifTK/NiftyNet/commit/90941ee2506a21b2793164ca34b8af054ff85f49) NiftyNet now fully supports 2D images without having to convert them to NiftyFormat. There is no need to fake 3-dimensional `spatial_window_size` either (although it is perfectly ok if you do).

NiftyNet currently supports loading images from OpenCV, Scikit-Image and PIL/Pillow, assuming that you have the corresponding libraries installed. You can specify a loader in the config file, or it will automatically try to find one that can handle yout images.

For more information check [image_loader.py](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/io/image_loader.py).

Example configuration file:

```
[images]
path_to_search = ~/data/test_image_segmentation/
filename_contains = bmp
spatial_window_size = (224, 224)
interp_order = 1
loader = opencv

[masks]
path_to_search = ~/data/test_image_segmentation/
filename_contains = _mask
spatial_window_size = (224, 224)
interp_order = 0
loader = skimage
```
