### ISSUE TITLE
interpolation order

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNet#138]
Make sure `interp_order` defined in NN is interpreted consistently across interface calls including `scipy.ndimage.zoom` and `sitk.ResampleImageFilter`.

**Comment by fepegar** [comment]
As a reference:

SimpleITK interpolators:
```python
 1: sitk.sitkNearestNeighbor
 2: sitk.sitkLinear
 3: sitk.sitkBSpline
 4: sitk.sitkGaussian
 6: sitk.sitkHammingWindowedSinc
 7: sitk.sitkCosineWindowedSinc
 8: sitk.sitkWelchWindowedSinc
 9: sitk.sitkLanczosWindowedSinc
10: sitk.sitkBlackmanWindowedSinc
```

In NiftyNet:
https://github.com/NifTK/NiftyNet/blob/a49fe8d7e3951cd15c19cf3ed17bb036e28bc4f9/niftynet/layer/rand_elastic_deform.py#L109-L116

In `scipy.ndimage.zoom`:
> order : int, optional
The order of the spline interpolation, default is 3. The order has to be in the range 0-5.

I don't know much about splines, but I think order 0 is equivalent to nearest neighbour and order 1 is equivalent to linear.

All the details should be explained in the docs
https://niftynet.readthedocs.io/en/latest/config_spec.html#interp-order

Maybe the parameter could be passed as a string instead of a number, for example:
```ini
interp_order = nearest
interp_order = linear
interp_order = bspline
```
