### ISSUE TITLE
More information on samples per volume 

### ISSUE THREAD

**Issue by kennethaweberii** [NifTK/NiftyNet#20]
Hello NiftyNet Team,

Could you provide more information on the sample_per_volume training parameter? How does increasing or decreasing this parameter affect training?

Thanks,

Ken

**Comment by wyli** [comment]
Hi @kennethaweberii, very briefly the input pipeline can be summarised as (load image volumes) -> (apply volume-level augmentation) -> (sample image windows from the volumes to form a training data batch). `sample_per_volume` controls the trade-off between batch data loading speed and
'diversity' of a batch. 

For example, if `batch_size=32` and `sample_per_volume=1`,  it'll call volume loading+volume transformation functions 32 times in order to generate a batch (one window is generated per volume); if `batch_size=32` and `sample_per_volume=32`, only one volume will be loaded, and 32 image windows will be generated from the volume.

hope this helps!
