### ISSUE TITLE
Feature request:  upsampling layers

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNet#279]
feature map upsampling is currently implemented using deconvolution,
and would be great to achieve the same spatial dimensionality changes with:
- [x] linear interpolations + convolution (niftynet/layer/linear_resize + conv)
- [x] sub-pixel convolution layer ([Shi et al.](https://arxiv.org/abs/1609.05158)) (merged PR https://github.com/NifTK/NiftyNet/pull/341)

**Comment by stian-johnsen** [comment]
I have implemented the sub-pixel net in PR https://github.com/NifTK/NiftyNet/pull/341.
The network is rather tricky to train, and training and inference require a separate driver script, since to the best of my knowledge NiftyNet cannot handle applications where the output image geometry differs from the input image geometry by an essentially random factor.
Also, the outputs are rather noisier than I'd like.

The repo with the driver script can be merged too, if requested.
