### ISSUE TITLE
A question about sample_per_volume and resize in promise2012 demo

### ISSUE THREAD

**Issue by EdwardMa12593** [NifTK/NiftyNet#32]
Dear all,
In the [demos/PROMISE12/promise12_demo_train_config.ini](https://github.com/NifTK/NiftyNet/blob/dev/demos/PROMISE12/promise12_demo_train_config.ini), the two parameters are set as `window_sampling = resize` and `sample_per_volume = 4`.
In this case, what is the `sampler_resize` output?
It seems the `sample_per_volume` is useless in this case. Because in [def initialise_resize_sampler(self):](https://github.com/NifTK/NiftyNet/blob/dev/niftynet/application/segmentation_application.py), `sampler_resize` is not used.
```python
    def initialise_resize_sampler(self):
        self.sampler = [[ResizeSampler(
            reader=reader,
            data_param=self.data_param,
            batch_size=self.net_param.batch_size,
            shuffle_buffer=self.is_training,
            queue_length=self.net_param.queue_length) for reader in
            self.readers]]
```
Besides, what is the role of `sampler_resize` in `segmentation_application`? For a segmentation task, I'm confused why resizing the input image (such as a `512*512*125` volume)  into a `64*64*64` spatial window? Instead, sampling some `64*64*64` image patches from an image volume seems more reasonable.
And the segmentation results in the test dataset do not match very well. Would it be possible for you to tell me what is the possible reason?
Following are some results of case4.
- ![Markdown](http://i2.bvimg.com/595387/79a020ba0a270739.png)
- ![Markdown](http://i2.bvimg.com/595387/58396cd6f006fb92.png)

Looking forward to your reply.
Best wishes,
Edward

**Comment by wyli** [comment]
Hi @EdwardMa12593 Yes, `sample_per_volume` parameter is actually ignored; that is, given one volume input, the sampler would always generate one window (by resizing the input). 

The sampling strategy and window size are free system parameters, a uniform sampling of `64x64x64` windows could be another option... if it turns out to be a better choice for segmentation please do consider submitting the model to the [model zoo](https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNetExampleServer/blob/master/model_zoo.md) :) 

For the final problem, it seems the mismatch is caused by the anisotropic resizing, could you please elaborate the steps to replicate the results? many thanks!

**Comment by EdwardMa12593** [comment]
Dear @wyli 
Thanks for your reply.
Is there a guideline about how to submit the model to the model zoo?
I'm not allowed to register [CMICLab](https://cmiclab.cs.ucl.ac.uk/users/sign_in).
