### ISSUE TITLE
Question about samplers

### ISSUE THREAD

**Issue by somsol** [NifTK/NiftyNet#43]
Hi NiftyNet team,

From what I understand by looking at the sampler codes, the uniform sampler randomly selects a location from the entire volume and crops the desired window size. I guess there's no guarantee that the training volumes are fully covered/used by the end of the training process. Is there a way to train a 3D network with an **overlapping** sliding window approach (grid sampler is not overlapping) that keeps track of what windows have been used so far for each data? Such a sampler would be useful to make sure we're using every single pixel in training. 

Thanks

**Comment by Zach-ER** [comment]
Hi there, 

thanks for the question: 

We don't currently support that functionality, although it could be added (it's the sampler that's used to generate the images in inference). 

I think that in general, we haven't really seen a use for this: while it's true that it would get every pixel to train with, you still have the case that some pixels are trained more than others (because some are on the border, for example). 

What's the special benefit to using every pixel in training deterministically, rather than doing a uniform sampling?

**Comment by somsol** [comment]
If the dataset is quite small, wouldn't splitting each data into all possible sub-volumes (or with a stride smaller than window size) effectively increase the dataset compared to random sampling?

**Comment by Zach-ER** [comment]
Methods of data augmentation (such as rotating or zooming) are probably better than just taking each sub-volume (although, you could do both). If you have these options on, it is v. unlikely you'll get the same patch twice (because it will be augmented differently).

**Comment by somsol** [comment]
Besides training, wouldn't we benefit from spatially overlapping windows in inference? specifically, We would be able to reduce boundary artifacts seen when using grid_sampler by a postprocessing step in the overlapping regions.

**Comment by Zach-ER** [comment]
Yes, this is indeed true. 

You can already specify a border for inference, such that it only returns the results from the 'inside' of the patch. This can be implemented with something like` border=20,20,20` under the `[INFERENCE]` part of the configuration file. 

See http://niftynet.readthedocs.io/en/dev/config_spec.html#inference for more information.

**Comment by somsol** [comment]
Thanks for pointing this out. 

 I am using the dense-vnet network, which outputs the same voxel size volume as the input (N==D), so according to description under [INFERENCE], I should set border =0, 0, 0. 

To be more clear what I am saying:
Since the entire volume cannot be fed into the GPU or it's not divisible by 8, I need to apply the network to sub-volumes. What I meant by 'boundary artifact' was the sudden jumps I see between the windows that are sampled with the grid_sampler. If I set the border to something like border = 20,20,20, How will the overlapping sections be interpreted? Will the last window processing that section determine the final values in these areas? 
What I want to do is an averaging of the probability values in the overlapping sections.

**Comment by Zach-ER** [comment]
I think if you set the border to 20, 20, 20: instead of tiling windows of `i x i x i ` it will tile windows of size `[i-40] x [i-40] x [i-40]`. Thus each pixel in that inner area is only processed once for output and that is the value that will be given. 

If  you really want to try the method of doing each voxel several times and averaging, you could do something like padding your images outside niftynet to get a different set of windows. My suspicion is that it won't change much, but could be worth a try.

**Comment by somsol** [comment]
Thanks for the clarification, I appreciate it.
