### ISSUE TITLE
Too many constraints for the size of the input [DeepMedic]

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#79]
Hi, thanks for the nice work. 

I have trouble deciding the size of the input for deepmedic network. It looks like the size has to be the multiples of 3 (d_factor) based on these constraintss: (deepmedic.py)
`assert self.d_factor % 2 == 1  # to make the downsampling centered
        assert (layer_util.check_spatial_dims(
            images, lambda x: x % self.d_factor == 0))
        assert (layer_util.check_spatial_dims(
            images, lambda x: x % 2 == 1))  # to make the crop centered
        assert (layer_util.check_spatial_dims(
            images,
            lambda x: x > self.d_factor * 16))  # required by receptive field`
        

However, when I chose (81,81,81) as the spatial_window_size, it complaints that 

`ValueError: Dimension size must be evenly divisible by 35937 but is 531441 for 'worker_0/loss_function/Reshape_1' (op: 'Reshape') with input shapes: [81,81,81,1], [2] and with input tensors computed as partial shapes: input[1] = [35937,?].`

Shouldn't the size be freely chosen? I may be wrong but I think that the code may lack some flexibility here. Besides, the input size in the original paper is 27^3, but it cannot be used here since it violates lambda x: x > self.d_factor * 16). I'm wondering how much is the code here modified from the one used in the original paper, and what input size should we use? Thanks.

**Comment by wyli** [comment]
Hi @YilinLiu97  there are two pathways in the network (fig 5 https://arxiv.org/abs/1603.05959), these constraints ensure a consistent shape of the final feature maps in both pathways.

Typical parameters for 3d segmentation:
-- training
image spatial window size = 57, label spatial window size = 9
-- inference
image spatial window size = 105, label spatial window size = 57

you could adjust batch size according to your GPU memory size.

We implement the network based on the paper and I can replicate (with a small variation due to the random factors) the results reported in the paper with NiftyNet.

**Comment by pldelisle** [comment]
> I'm wondering why it has to go through so many iterations for inference? It seems to run forever and I haven't been able to see the segmented result yet...

I was trying NiftyNet too and had the same problem. It takes forever to do inference. But I think this is related to the `border` variable in the configuration file you use. 

Still trying to find a way to optimize this.
